[workspace]

members = [
    "./hpack",
    "./huffman",
    "./protos",
]

[patch.crates-io]
httlib-hpack = { path = "./hpack" }
httlib-huffman = { path = "./huffman" }
httlib-protos = { path = "./protos" }
